// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDE1e3srJQnAXdo8tOrF6D4vVJCivt-lw',
    appId: '1:273263990467:web:5061f74a37c770373f7476',
    messagingSenderId: '273263990467',
    projectId: 'slangsavvy-a95e0',
    authDomain: 'slangsavvy-a95e0.firebaseapp.com',
    storageBucket: 'slangsavvy-a95e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUb2q1SZJr7uxpEOfUINrPmyTwhjqJ3Ik',
    appId: '1:273263990467:android:36ca8cedb0957aed3f7476',
    messagingSenderId: '273263990467',
    projectId: 'slangsavvy-a95e0',
    storageBucket: 'slangsavvy-a95e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD335d43Xgzi0AK68aGAZo0P5Kip8YhwqE',
    appId: '1:273263990467:ios:aa4233607461faa93f7476',
    messagingSenderId: '273263990467',
    projectId: 'slangsavvy-a95e0',
    storageBucket: 'slangsavvy-a95e0.firebasestorage.app',
    iosBundleId: 'com.example.slangsavvy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD335d43Xgzi0AK68aGAZo0P5Kip8YhwqE',
    appId: '1:273263990467:ios:aa4233607461faa93f7476',
    messagingSenderId: '273263990467',
    projectId: 'slangsavvy-a95e0',
    storageBucket: 'slangsavvy-a95e0.firebasestorage.app',
    iosBundleId: 'com.example.slangsavvy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDE1e3srJQnAXdo8tOrF6D4vVJCivt-lw',
    appId: '1:273263990467:web:6c84e3c7b187ee973f7476',
    messagingSenderId: '273263990467',
    projectId: 'slangsavvy-a95e0',
    authDomain: 'slangsavvy-a95e0.firebaseapp.com',
    storageBucket: 'slangsavvy-a95e0.firebasestorage.app',
  );
}
